### ISSUE TITLE
Compilation fails with kernel 6.4.4

### ISSUE THREAD

**Issue by dimich-dmb** [anszom/vtty#10]
First error is
```
vtty.c:283:24: error: initialization of ‘void (*)(struct tty_struct *, const struct ktermios *)’ from incompatible pointer type ‘void (*)(struct tty_struct *, struct ktermios *)’ [-Werror=incompatible-pointer-types]
  283 |         .set_termios = vtty_set_termios,
```
Signature of `set_termios` in `struct tty_operations` changed since 6.0.0. It can be easily fixed with this [PR](https://github.com/anszom/vtty/pull/9).

Second error is 
```
vtty.c:449:54: error: implicit declaration of function ‘kernel_termios_to_user_termios’ [-Werror=implicit-function-declaration]
  449 |                                         copystatus = kernel_termios_to_user_termios((struct termios2 __user*)ptr, &port->oob_data.termios);
```
`#include <linux/termios_internal.h>` doesn't fix it because the symbol seems no longer exported. Trying to figure out how to solve it.

**Comment by dimich-dmb** [comment]
Replacing kernel_termios_to_user_termios() with copy_to_user() seems fixes the error.

**Comment by anszom** [comment]
I'm not sure if this is the right approach in general, it's my understanding that on some architectures the user & kernel structs have different layout...

**Comment by anszom** [comment]
It turns out that the layout is the same, but the structure fields are interpreted differently on sparc. I don't have any better ideas (short of pestering kernel maintainers to export kernel_termios_to_user_termios), so I went with copy_to_user, but added an #ifdef that will error out on sparc.
