### ISSUE TITLE
cannot install module

### ISSUE THREAD

**Issue by christianrauch** [anszom/vtty#13]
Running `make` successfully builds the module `/vtty.ko`, but installing via `make modules_install` fails:
```
$ sudo make modules_install 
make -C /lib/modules/6.2.0-32-generic/build M= modules
make[1]: Verzeichnis „/usr/src/linux-headers-6.2.0-32-generic“ wird betreten
make[2]: *** Keine Regel vorhanden, um das Ziel „arch/x86/entry/syscalls/syscall_32.tbl“, 
  benötigt von „arch/x86/include/generated/uapi/asm/unistd_32.h“, zu erstellen.  Schluss.
make[1]: *** [arch/x86/Makefile:248: archheaders] Fehler 2
make[1]: Verzeichnis „/usr/src/linux-headers-6.2.0-32-generic“ wird verlassen
make: *** [Makefile:5: modules] Fehler 2
```

That is more or less saying:

> *** No rule exists to create target 'arch/x86/entry/syscalls/syscall_32.tbl' required by 'arch/x86/include/generated/uapi/asm/unistd_32.h'. Ending.

Are there instructions on how to build the module?

**Comment by christianrauch** [comment]
Further to this, I cannot load the module:
```
$ sudo insmod vtty.ko 
insmod: ERROR: could not insert module vtty.ko: Invalid module format
```
and in dmesg:
```
module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 0000000066289482, val ffffffffc1542740
```

**Comment by anszom** [comment]
You mention that this issue is fixed by #15, but I'm not sure how this would help. Something to do with the environment? I'm curious - I haven't seen these errors before

**Comment by anszom** [comment]
Ok nevermind, I see it. The makefile was using the PWD environment variable. I've modified it to just call `pwd`

**Comment by christianrauch** [comment]
> Ok nevermind, I see it. The makefile was using the PWD environment variable. I've modified it to just call `pwd`

It was fixed by installing via `sudo -E` as this forwards the environment variables.
